### ISSUE TITLE
SVG boundaries/positioning not being respected?

### ISSUE THREAD

**Issue by esamelson** [mapbox/spritezero#38] opened 2016-11-04 23:19 UTC
Hello,

I'm trying to create a sprite which includes many images similar to the one below (SVG code). All are in SVG format, and I've modified them adding the "transform" property on line 16, for translating and rotating the image, and changing the document size on line 4 (was originally 50x75).

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 20.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="260px" height="260px" viewBox="0 0 260 260" enable-background="new 0 0 260 260" xml:space="preserve">
<g id="Layer_1_1_">
</g>
<g id="Layer_2_1_">
	<g>
		<g>
			<polygon fill="#FFFFFF" points="25.1,27.7 25,27.7 25,27.7 			"/>
			<path fill="none" d="M25,27.7L25,27.7L25,27.7L25,27.7z M25,27.7L25,27.7L25,27.7L25,27.7z M12.7,24.8l0.1,0.1h24.4l0.1-0.1H12.7
				z M25,27.7L25,27.7L25,27.7L25,27.7z"/>
		</g>
	</g>
	<g>
		<g transform="translate(105) rotate(0, 25, 130)">
			<path fill="#FFFFFF" d="M25,27.7L25,27.7L25,27.7L25,27.7z"/>
			<path fill="#231F20" d="M0.3,24.9V35h19.6v39.2h10.2V35h19.6V24.9H0.3z M46.8,32.1H27.2v39.2h-4.4V32.1H3.2v-4.4h43.7L46.8,32.1
				L46.8,32.1z M25.1,27.7L25.1,27.7L25.1,27.7L25.1,27.7z"/>
			<path d="M25,27.7L25,27.7L25,27.7L25,27.7z"/>
			<polygon fill="#FFFFFF" points="46.8,27.8 46.8,32.1 27.2,32.1 27.2,71.3 22.8,71.3 22.8,32.1 3.2,32.1 3.2,27.8 			"/>
		</g>
	</g>
</g>
<circle fill="none" cx="25" cy="10.9" r="8.8"/>
</svg>
```

If I run svg2png directly on this file, the output is what I expect - a 260x260 px image with the graphic centered above the horizon:
![anchor_shadow-0](https://cloud.githubusercontent.com/assets/19958240/20025239/b8446866-a2a9-11e6-88fb-16ab0faf5e0b.png)

However, when running spritezero, it puts the graphic arbitrarily in the lower right hand corner of this area, as seen below:
![sprite](https://cloud.githubusercontent.com/assets/19958240/20025309/6137aa0a-a2aa-11e6-97c0-5ae458ba82b6.png)

As I'm trying to create a sprite with a large number of similar graphics (with varying sizes), this is causing quite an issue. Am I doing something wrong with modifying the SVG? I'm confused as to why I'm getting a different output from svg2png - isn't this what spritezero is using in the background?

Any help or advice would be greatly appreciated. Thanks so much.

**Comment by tmcw** [comment] 2017-03-20 18:59
Ping @bhousel - any ideas?

**Comment by zilvinelis** [comment] 2018-01-26 13:17
Any ideas about this issue?
We are experiencing the same - images get centered in their respective containers in output png.

**Comment by bhousel** [comment] 2018-01-26 14:58
Sorry @zilvinelis, @esamelson, I haven't had time to dig into this.  

Spritezero is really just a wrapper around whatever Mapnik does.  It doesn't contain any SVG processing code.

https://github.com/mapbox/spritezero/blob/621c660240feaee5906129f56afe1b52d066ad13/index.js#L118-L129

Maybe we should look into alternatives like `svg2png` ?   Mapnik will probably never rasterize SVGs as well as an actual headless browser will.  

For context, [svg2png](https://github.com/domenic/svg2png) is a wrapper around PhantomJS, which is headless webkit.  A better and more modern thing could be built with [puppeteer](https://github.com/GoogleChrome/puppeteer) and headless Chrome.

**Comment by zilvinelis** [comment] 2018-01-26 19:41
@bhousel, thanks for the quick response. I'll look into suggested alternatives if I have enough time (simply switching to svg2png seems to be the easiest way). Currently our fallback is to create *.png sprite using designer tools and to craft .json manually:)

**Comment by springmeyer** [comment] 2020-04-13 16:08
I presume this is fixed in latest mapnik, which saw many improvements to svg positioning after https://github.com/mapnik/mapnik/pull/4113. If people are still seeing issues, please create a new issue and document exactly what script you are using to generate the output, so that it is easily reproducible (this ticket has no reproducible testcase to confirm this problem is still present or not).

**Closed by springmeyer** 2020-04-13 16:08 UTC
